title: thestayathomedad
baseurl: ""
url: ""

collections_dir: content
collections:
  blog:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: blog
    values:
      layout: post
