collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL part, no spaces" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Video URL", name: "video", widget: "string", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Order", name: "weight", widget: "number", default: 0 }
      - { label: "Published", name: "published", widget: "boolean", default: true }
