backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Video URL", name: "video", widget: "string", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Published", name: "published", widget: "boolean", default: true }
